rename files

diff --git a/set_polkit_default_privs b/set_polkit_default_privs
--- a/set_polkit_default_privs
+++ b/set_polkit_default_privs
@@ -1,5 +1,5 @@
 #! /bin/bash
-# This module sets policykit permssions
+# This module sets policykit default permissions
 # Copyright (C) 2008 SUSE Linux Products GmbH, Nuernberg, Germany.
 #
 # This program is free software; you can redistribute it and/or modify
@@ -16,30 +16,38 @@
 # along with this program; if not, write to the Free Software
 # Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 #
-# Based on SuSEconfig.permssions
+# Based on SuSEconfig.permissions
 #
 # Author: Ludwig Nussel  <lnussel@suse.de> 2008
 #
 
 . /etc/sysconfig/security || exit 1
 
+if [ -z "$POLKIT_DEFAULT_PRIVS" ]; then
+	case "$PERMISSION_SECURITY" in
+		*secure*|*paranoid*) POLKIT_DEFAULT_PRIVS="restrictive" ;;
+		*) POLKIT_DEFAULT_PRIVS="standard" ;;
+	esac
+fi
+
 mode=""
-case "$CHECK_PERMISSIONS" in
-    set) mode="-set" ;;
+case "$CHECK_POLKIT_PRIVS" in
+    set|"") mode="-set" ;;
     warn) ;;
-    no|"") exit 0 ;;
-    *) echo "invalid value '$CHECK_PERMISSIONS' for \$CHECK_PERMISSIONS" >&2 ;;
+    no) exit 0 ;;
+    *) echo "invalid value '$CHECK_POLKIT_PRIVS' for \$CHECK_POLKIT_PRIVS, using 'set'" >&2; mode="-set" ;;
 esac
 
 # collect files that contain permission specifications
+# we need to use a useful order
 #
-# 1. central fixed permissions file
+# 1. common privileges file (we have none yet)
 files=""
 
-# 2. central easy, secure paranoid as those are defined by SUSE
-for level in $PERMISSION_SECURITY; do 
+# 2. relaxed, standard, restrictive as those are defined by SUSE
+for level in $POLKIT_DEFAULT_PRIVS; do 
     case "$level" in
-	easy|secure|paranoid)
+	relaxed|standard|restrictive)
 	    if [ -e /etc/polkit-permissions.$level ]; then
 		files="$files /etc/polkit-permissions.$level"
 	    fi
@@ -56,19 +64,19 @@ pkgfiles=(`for i in ${pkgfiles[@]}; do echo $i; done | /usr/bin/sort -u`)
 for file in ${pkgfiles[@]}; do
     file=/etc/polkit-permissions.d/$file
     [ -e $file ] && files="$files $file"
-    for level in $PERMISSION_SECURITY; do 
+    for level in $POLKIT_DEFAULT_PRIVS; do 
 	[ -e $file.$level ] && files="$files $file.$level"
     done
 done
 
 # 4. central permissions files with user defined level incl 'local'
-for level in $PERMISSION_SECURITY; do 
+for level in $POLKIT_DEFAULT_PRIVS; do 
     case "$level" in
-	easy|secure|paranoid) continue ;;
+	relaxed|standard|restrictive) continue ;;
     esac
     if [ -e /etc/polkit-permissions.$level ]; then
 	files="$files /etc/polkit-permissions.$level"
     fi
 done
 
-polkit-chkstat $mode $files
+chkstat-polkit $mode $files
